### ISSUE TITLE
Return an appropiate error instead of nil if Exists fail

### ISSUE THREAD

**Issue by adelowo** [spf13/afero#124]
Hi,

Currently, in https://github.com/spf13/afero/blob/master/util.go#L313-L319, nil is return (as an error) even though `os.IsNotExist` returns true.. Ideally that is supposed to be an error denoting the file does not exist (`os.PathError` or a concrete error type ? )

Another thing is most go code end up like

```go

if _, err := Exists("path"); err != nil {
   //file does not exist
}

```

But the above would actually fail since error is nil and the underscored value is falsy.

**Comment by mbertschler** [comment]
I think this is working as intended. If there is an error in reading the file information that is not a not exists error, the function can't actually tell you if it exists or not.
- `true, nil` returned means it exists.
- `false, nil` returned means it doesn't exist.
- `false, error` returned means it is unknown if the file exists because it could not be read.
This could probably happen if you don't have permissions to read the file.

The right way to use in the code would be:
```go
exists, err := afero.Exists("path")
if err != nil {
   //file existence is unknown, something else happened
} else if !exists {
   //file does not exist
}

```
